export const MAIN_PAGE="/protected/home"

export const allTrueSettings = {
    testsEnabled: true,
    medsEnabled: true,
    statusEnabled: true,
    personalityEnabled: true,
    castrationEnabled: true,
    dogInteractionEnabled: true,
    catInteractionEnabled: true,
    childrenInteractionEnabled: true,
    dewormingEnabled: true,
    healthEnabled: true,
    storyEnabled: true,
    infoForCarerEnabled: true,
  };
export const catsNewbieSettings = {
    testsEnabled: true,
    medsEnabled: true,
    statusEnabled: false,
    personalityEnabled: true,
    castrationEnabled: false,
    dogInteractionEnabled: false,
    catInteractionEnabled: false,
    childrenInteractionEnabled: false,
    dewormingEnabled: false,
    healthEnabled: false,
    storyEnabled: true,
    infoForCarerEnabled: true,
    bedEnabled: false,
    walkEnabled: false,
  };
export const dogsNewbieSettings = {
    testsEnabled: true,
    medsEnabled: true,
    statusEnabled: true,
    personalityEnabled: true,
    castrationEnabled: false,
    dogInteractionEnabled: false,
    catInteractionEnabled: false,
    childrenInteractionEnabled: false,
    dewormingEnabled: false,
    healthEnabled: false,
    storyEnabled: true,
    infoForCarerEnabled: true,
    bedEnabled: true,
    walkEnabled: true,
  };